apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "ebs-sc"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 19Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-dynamic
  labels:
    purpose: ebs-dynamic-demo
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-sc 
---
apiVersion: v1
kind: Service
metadata:
  name: ebs-dynamic
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30007  
