kind: Pod
apiVersion: v1
metadata:
 name: env
spec:
 containers:
    name: env
    image: nginx
    env:
    - name: course
      value: Devops
    - name: trainer
      value: "Siva Kumar"
    - name: duration
      value: 120H    