apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    tier: web
    purpose: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      tier: web
      purpose: deployment
  template:
    metadata:
      labels:
        app: nginx
        tier: web
        purpose: deployment
    spec:
      containers:
        - name: nginx
          image: vemasaikumar/nginx:2.0.0
          ports:
          - containerPort: 80    
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    labels:
    app: nginx
    tier: web
    purpose: deployment
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80
    nodePort: 30007  



