apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs
spec:
  accessModes:
  - ReadWriteOnce  
  capacity:
    storage: 30Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-02c6bc87537ee23af
      