apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs
spec:
  storageClassName: ""
  volumeName: ebs
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  
---
apiVersion: v1
kind: Pod
metadata: 
  name: ebs
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx    
    volumeMounts: 
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim: 
      claimName: ebs
---
kind: Service
apiVersion: v1
metadata:
  name: ebs
spec:
  type: LoadBalancer
  selctor:
    purpose: "ebs-static-demo"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
