apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: ebs-stat
spec:
  storageClassName: ""
  volumeName: ebs-stat
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi  
---
apiVersion: v1
kind: Pod
metadata: 
  name: ebs-stat
  labels:
    purpose: "ebs-static-demo"
spec:
  nodeSelector: 
    topology.kubernetes.io/zone: us-east-1d
  containers:
  - name: nginx
    image: nginx    
    volumeMounts: 
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim: 
      claimName: ebs-stat